package Raft;
use strict;
use warnings;
use utf8;

our $VERSION = "0.01";

use Class::Accessor::Lite::Lazy new => 1, ro_lazy => [qw/config/];

# override it!!
sub load_config { die "this is abstract method." }
sub _build_config { shift->load_config() }

1;
__END__

=encoding utf-8

=head1 NAME

Raft - yet another web application framework

=head1 SYNOPSIS

    package MyApp;
    use parent qw/Raft/;
    use Raft::Config::Simple;
    sub load_config { Raft::Config::Simple->load(shift) }

=head1 DESCRIPTION

Raft is simple, readable, extensible web application framework based on L<Plack>.

=head1 METHODS

=over 4

=item C<< MyApp->new() >>

Create new context object.

=item C<< $app->config() >>

This method returns configuration information. It is generated by C<< $app->load_config() >>.

=back

=head1 DOCUMENTS

TODO!!

=head1 SUPPORTS

TODO: #raft at irc.perl.org is also available.

=head1 LICENSE

Copyright (C) karupanerura.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=head1 AUTHOR

karupanerura E<lt>karupa@cpan.orgE<gt>
